services:
  - type: web
    name: vibolsen-inventory-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
